apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ template "fullname" . }}
spec:
  args:
  - name: service
  metrics:
  - name: success-rate
    provider:
      job:
        metadata:
          annotations:
            service: "{{`{{args.service}}`}}"
          labels:
            service: "{{`{{args.service}}`}}"
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: curl
                image: curlimages/curl:8.1.1
                command:
                - curl
                args:
                - -v
                - --max-time
                - "1"
                - -sSf
                - -o
                - /dev/null
                - "{{`http://{{args.service}}/data`}}"
              restartPolicy: Never
