{{- if .Values.rollout.enable }}
# Create a rollout resource
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- if .Values.appLabel }}
      app: {{ .Values.appLabel }}
{{- else }}
      app: {{ template "fullname" . }}
{{- end }}
  # Reference an existing Deployment using workloadRef field
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "fullname" . }}
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10s}
        - setWeight: 60
        - pause: {duration: 10s}
        - setWeight: 80
        - pause: {duration: 10s}
{{- end }}
